#!/usr/bin/env ruby

require 'activejob-google_cloud_pubsub'
require 'optparse'

Version = ActiveJob::GoogleCloudPubsub::VERSION

opts = {
  require: './config/environment'
}
worker_args = {}

parser = OptionParser.new
parser.on '--[no-]require=PATH' do |v|
  opts[:require] = v
end
parser.on '--min_threads=N' do |v|
  worker_args[:min_threads] = v
end
parser.on '--max_threads=N' do |v|
  worker_args[:max_threads] = v
end
parser.parse ARGV

require opts[:require] if opts[:require]

pubsub = Google::Cloud::Pubsub.new
$stdout.sync = true
begin
  ActiveJob::GoogleCloudPubsub::Worker.new(pubsub: pubsub, **worker_args).run
rescue Interrupt
  exit
end
